
name: CI
on:
  push:
    branches:
      - develop
jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
       Project_Path: src/DateScanner.csproj
       Test_Project_Path: test/DateScanner.Test.csproj
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    
    # Test
    - name: Test
      run: dotnet test $env:Test_Project_Path

   
