
name: CI On nuget
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  publish:
    runs-on: windows-latest
    env:
       Project_Path: src/DateScanner.csproj
       Test_Project_Path: test/DateScanner.Test.csproj
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

    # Use Nerdbank.GitVersioning to set version variables: https://github.com/AArnott/nbgv
    - name: Use Nerdbank.GitVersioning to set version variables
      uses: aarnott/nbgv@v0.3
      with:
        setAllVars: true

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
        source-url: https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_Token: ${{secrets.NUGET_API_KEY}}

    # Test
    - name: Test
      run: dotnet test $env:Test_Project_Path

    #Pack  
    - name: Pack
      run: dotnet pack $env:Project_Path -c Release --output nupkgs -p:Version=$env:NBGV_NuGetPackageVersion --include-symbols --include-source

    #Deploy
    - name: Publish
      run: dotnet nuget push nupkgs/*.nupkg 
    
